ALTER TABLE properties ADD COLUMN IF NOT EXISTS homestead_exempt BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS county_parcel_id VARCHAR(50);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS property_sqft INTEGER;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS data_source VARCHAR(50);
