import { Router } from 'express';
import authRouter from './auth.js';
import stormsRouter from './storms.js';
import mapRouter from './map.js';
import dashboardRouter from './dashboard.js';
import propertiesRouter from './properties.js';
import leadsRouter from './leads.js';
import skipTraceRouter from './skipTrace.js';
import webhookRouter from './webhook.js';
import alertsRouter from './alerts.js';
import driftRouter from './drift.js';
import countiesRouter from './counties.js';
import crmRouter from './crm.js';
import estimatesRouter from './estimates.js';
import notificationsRouter from './notifications.js';
import searchRouter from './search.js';
import documentsRouter from './documents.js';
import roofMeasurementRouter from './roofMeasurement.js';
import onboardingRouter from './onboarding.js';
import adminRouter from './admin.js';
import paymentsRouter from './payments.js';
import materialsRouter from './materials.js';
import financingRouter from './financing.js';
import hearthWebhookRouter from './hearthWebhook.js';
import automationsRouter from './automations.js';
import invoicesRouter from './invoices.js';
import canvassingRouter from './canvassing.js';
import reportsRouter from './reports.js';
import workOrdersRouter from './workOrders.js';
import dripRouter from './drip.js';
import contractsRouter from './contracts.js';
import expensesRouter from './expenses.js';
import subcontractorsRouter from './subcontractors.js';
import territoriesRouter from './territories.js';
import disasterDeclarationsRouter from './disasterDeclarations.js';
import stormHistoryRouter from './stormHistory.js';
import dataApisRouter from './dataApis.js';

const router = Router();

router.use('/auth', authRouter);
router.use('/storms', stormsRouter);
router.use('/map', mapRouter);
router.use('/dashboard', dashboardRouter);
router.use('/properties', propertiesRouter);
router.use('/leads', leadsRouter);
router.use('/skip-trace', skipTraceRouter);
router.use('/webhooks', webhookRouter);
router.use('/alerts', alertsRouter);
router.use('/drift', driftRouter);
router.use('/counties', countiesRouter);
// Mount CRM sub-routers with public routes BEFORE the CRM auth router
router.use('/crm/financing', financingRouter);
router.use('/crm/contracts', contractsRouter);
router.use('/crm', crmRouter);
router.use('/crm/automations', automationsRouter);
router.use('/crm/invoices', invoicesRouter);
router.use('/crm/canvass-pins', canvassingRouter);
router.use('/crm/reports', reportsRouter);
router.use('/crm/work-orders', workOrdersRouter);
router.use('/crm/drip-sequences', dripRouter);
router.use('/estimates', estimatesRouter);
router.use('/notifications', notificationsRouter);
router.use('/search', searchRouter);
router.use('/documents', documentsRouter);
router.use('/roof-measurement', roofMeasurementRouter);
router.use('/onboarding', onboardingRouter);
router.use('/admin', adminRouter);
router.use('/payments', paymentsRouter);
router.use('/materials', materialsRouter);
router.use('/crm/expenses', expensesRouter);
router.use('/crm/subcontractors', subcontractorsRouter);
router.use('/crm/territories', territoriesRouter);
router.use('/webhooks/hearth', hearthWebhookRouter);
router.use('/disaster-declarations', disasterDeclarationsRouter);
router.use('/storm-history', stormHistoryRouter);
router.use('/data', dataApisRouter);

export default router;
